public class AccHandler {
   public static void method1(){

	system.debug('statement 1');
	system.debug('statement 2 updated form mar branch...');
   
   }
   public static void method2(){
         system.debug('statement 1');
         system.debug('statement 2 updated form mar branch...');
         
         }
   public static void method3(){
            system.debug('statement 1');
            system.debug('statement 2 updated form mar branch...');
            }



}
